"""add comments table

Revision ID: 147d42584675
Revises: e061a6b8cd6
Create Date: 2016-01-27 14:35:23.637144

"""

# revision identifiers, used by Alembic.
revision = '147d42584675'
down_revision = 'e061a6b8cd6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_utc', sa.Float(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('body', sa.UnicodeText(), nullable=False),
    sa.Column('ups', sa.Integer(), nullable=False),
    sa.Column('downs', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    ### end Alembic commands ###
