"""add submissions table

Revision ID: 3c6f2c76ca55
Revises: 
Create Date: 2016-01-27 11:06:58.772187

"""

# revision identifiers, used by Alembic.
revision = '3c6f2c76ca55'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_utc', sa.Float(), nullable=False),
    sa.Column('fullname', sa.String(), nullable=False),
    sa.Column('subreddit', sa.String(), nullable=False),
    sa.Column('subreddit_id', sa.String(), nullable=False),
    sa.Column('permalink', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('title', sa.Unicode(), nullable=False),
    sa.Column('selftext', sa.UnicodeText(), nullable=True),
    sa.Column('ups', sa.Integer(), nullable=False),
    sa.Column('downs', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('num_comments', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submissions')
    ### end Alembic commands ###
