"""remove submissions subreddit column

Revision ID: e061a6b8cd6
Revises: 3c6f2c76ca55
Create Date: 2016-01-27 12:37:21.702177

"""

# revision identifiers, used by Alembic.
revision = 'e061a6b8cd6'
down_revision = '3c6f2c76ca55'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_column('subreddit')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subreddit', sa.VARCHAR(), nullable=False))

    ### end Alembic commands ###
